# Generated by Django 5.2.7 on 2025-10-13 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('read', 'Okundu'), ('replied', 'Yanıtlandı')], default='new', max_length=20, verbose_name='Durum')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Admin Yanıtı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Görsel')),
                ('category', models.CharField(choices=[('dogs', 'Köpekler'), ('cats', 'Kediler'), ('clinic', 'Klinik'), ('team', 'Ekip')], max_length=50, verbose_name='Kategori')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Etiketler')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, unique=True, verbose_name='Sayfa')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, verbose_name='İçerik')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayfa İçeriği',
                'verbose_name_plural': 'Sayfa İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('specialty', models.CharField(max_length=200, verbose_name='Uzmanlık Alanı')),
                ('bio', models.TextField(blank=True, verbose_name='Biyografi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='veterinarians/', verbose_name='Profil Fotoğrafı')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Deneyim (Yıl)')),
                ('education', models.TextField(blank=True, verbose_name='Eğitim')),
                ('certifications', models.TextField(blank=True, verbose_name='Sertifikalar')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veteriner Hekim',
                'verbose_name_plural': 'Veteriner Hekimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('excerpt', models.TextField(max_length=500, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Öne Çıkan Görsel')),
                ('category', models.CharField(default='Genel', max_length=100, verbose_name='Kategori')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Etiketler')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=20, verbose_name='Durum')),
                ('views', models.IntegerField(default=0, verbose_name='Görüntülenme')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='api.veterinarian', verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Evcil Hayvan Adı')),
                ('pet_type', models.CharField(max_length=50, verbose_name='Hayvan Türü')),
                ('pet_breed', models.CharField(blank=True, max_length=100, verbose_name='Irk')),
                ('pet_age', models.CharField(max_length=50, verbose_name='Yaş')),
                ('owner_name', models.CharField(max_length=200, verbose_name='Sahip Adı')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('service', models.CharField(max_length=200, verbose_name='Hizmet')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.veterinarian', verbose_name='Veteriner')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['date', 'time'],
            },
        ),
    ]
