# Generated by Django 4.2.7 on 2025-10-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='expertise_areas',
            field=models.TextField(blank=True, help_text='Her satıra bir uzmanlık alanı', verbose_name='Uzmanlık Alanları'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mezuniyet Yılı'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='working_days',
            field=models.CharField(blank=True, help_text='Virgülle ayırın: Pazartesi,Salı,Çarşamba', max_length=200, verbose_name='Çalışma Günleri'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='working_hours',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=50, verbose_name='Çalışma Saatleri'),
        ),
    ]
