# Generated by Django 4.2.7 on 2025-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_veterinarian_expertise_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarian',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='achievements',
            field=models.TextField(blank=True, help_text='Her satıra bir başarı', verbose_name='Başarılar ve Ödüller'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuma'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pazartesi'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cumartesi'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='sunday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pazar'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Perşembe'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Salı'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Çarşamba'),
        ),
    ]
