# Generated by Django 4.2.7 on 2025-10-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_veterinarian_working_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.TextField(verbose_name='Görsel URL'),
        ),
    ]
