# Generated by Django 4.2.7 on 2025-10-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='sections',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Bölümler'),
        ),
    ]
