# Generated by Django 4.2.7 on 2025-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pagecontent_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='faqs',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='SSS (Sıkça Sorulan Sorular)'),
        ),
    ]
