# Generated by Django 4.2.7 on 2025-10-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pagecontent_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Her özellik bir liste öğesi olarak eklenecek', null=True, verbose_name='Neler Sunuyoruz (Özellikler)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, help_text='Her adım sırayla gösterilecek', null=True, verbose_name='Süreç Nasıl İşler (Adımlar)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='vaccination_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='{"puppies": "Yavru bilgisi", "adult": "Yetişkin bilgisi", "rabies": "Kuduz bilgisi"}', null=True, verbose_name='Aşı Takvimi'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='sections',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Bölümler'),
        ),
    ]
