# Generated by Django 4.2.7 on 2025-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pagecontent_features_pagecontent_process_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='🏥', max_length=10, verbose_name='İkon')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('short_description', models.TextField(max_length=500, verbose_name='Kısa Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order', 'title'],
            },
        ),
    ]
