# Generated by Django 5.2.7 on 2025-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.TextField(default='Evcil dostlarınızın sağlığı ve mutluluğu için 10+ yıldır hizmetinizdeyiz', verbose_name='Hero Alt Başlık')),
                ('stats', models.JSONField(default=list, help_text='[{"number": "10+", "label": "Yıllık Tecrübe"}, ...]', verbose_name='İstatistikler')),
                ('story_title', models.CharField(default='Hikayemiz', max_length=200, verbose_name='Hikaye Başlık')),
                ('story_paragraph_1', models.TextField(default='', verbose_name='Hikaye Paragraf 1')),
                ('story_paragraph_2', models.TextField(default='', verbose_name='Hikaye Paragraf 2')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hakkımızda Sayfası',
                'verbose_name_plural': 'Hakkımızda Sayfası',
            },
        ),
    ]
