# Generated by Django 5.0.1 on 2025-10-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Bizimle İletişime Geçin', max_length=200, verbose_name='Ana Başlık')),
                ('hero_subtitle', models.TextField(default='Sevimli dostlarınızın sağlığı için her zaman yanınızdayız. 7/24 hizmetinizdeyiz!', verbose_name='Alt Başlık')),
                ('phone_number', models.CharField(default='(0212) 123 45 67', max_length=50, verbose_name='Telefon Numarası')),
                ('phone_label', models.CharField(default='7/24 Acil Hat', max_length=100, verbose_name='Telefon Etiketi')),
                ('whatsapp_number', models.CharField(default='0555 123 45 67', max_length=50, verbose_name='WhatsApp Numarası')),
                ('whatsapp_label', models.CharField(default='Hızlı İletişim', max_length=100, verbose_name='WhatsApp Etiketi')),
                ('email_primary', models.EmailField(default='info@petkey.com', max_length=254, verbose_name='Birincil E-posta')),
                ('email_secondary', models.EmailField(blank=True, default='destek@petkey.com', max_length=254, verbose_name='İkincil E-posta')),
                ('address_line1', models.CharField(default='Kadıköy, İstanbul', max_length=200, verbose_name='Adres Satır 1')),
                ('address_line2', models.CharField(blank=True, default='Türkiye', max_length=200, verbose_name='Adres Satır 2')),
                ('google_maps_url', models.URLField(default='https://www.google.com/maps/place/Kad%C4%B1k%C3%B6y,+Istanbul/@40.9887328,29.0242891,13z', verbose_name='Google Maps URL')),
                ('google_maps_embed', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48377.833789145195!2d29.00782952167968!3d40.98876200000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab9bdf0702a83%3A0xe9e46e5fdbf96af!2zS2FkxLFrw7Z5LCDEsHN0YW5idWw!5e0!3m2!1str!2str!4v1647000000000!5m2!1str!2str', verbose_name='Google Maps Embed URL')),
                ('working_hours', models.JSONField(default=list, help_text='[{"day": "Pazartesi - Cuma", "hours": "09:00 - 19:00"}, ...]', verbose_name='Çalışma Saatleri')),
                ('why_contact_us', models.JSONField(default=list, help_text='[{"icon": "🏥", "title": "Başlık", "description": "Açıklama"}, ...]', verbose_name='Neden Bize Ulaşmalısınız')),
                ('emergency_title', models.CharField(default='🚨 Acil Durumlar İçin', max_length=200, verbose_name='Acil Durum Başlık')),
                ('emergency_subtitle', models.TextField(default='Evcil dostunuzun acil bir durumu mu var? Hemen bizi arayın!', verbose_name='Acil Durum Alt Başlık')),
                ('emergency_phone', models.CharField(default='(0212) 123 45 67', max_length=50, verbose_name='Acil Hat Telefon')),
                ('emergency_whatsapp', models.CharField(default='0555 123 45 67', max_length=50, verbose_name='Acil WhatsApp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İletişim Sayfası',
                'verbose_name_plural': 'İletişim Sayfası',
            },
        ),
    ]
