# Generated by Django 5.2.7 on 2025-10-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('homepage', 'Ana Sayfa'), ('services', 'Hizmetler'), ('blog', 'Blog'), ('about', 'Hakkımızda'), ('contact', 'İletişim'), ('global', 'Genel Ayarlar')], max_length=50, unique=True, verbose_name='Sayfa')),
                ('title', models.CharField(blank=True, help_text='Optimal: 50-60 karakter', max_length=70, verbose_name='Meta Başlık')),
                ('description', models.CharField(blank=True, help_text='Optimal: 150-160 karakter', max_length=170, verbose_name='Meta Açıklama')),
                ('keywords', models.CharField(blank=True, help_text='Virgül ile ayırın', max_length=500, verbose_name='Anahtar Kelimeler')),
                ('og_image', models.CharField(blank=True, default='/og-image.jpg', help_text='Önerilen: 1200x630px', max_length=500, verbose_name='Open Graph Görseli')),
                ('canonical', models.URLField(blank=True, max_length=500, verbose_name='Canonical URL')),
                ('site_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Adı')),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter Handle')),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter URL')),
                ('google_analytics_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Analytics ID')),
                ('google_search_console_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Search Console ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Ayarı',
                'verbose_name_plural': 'SEO Ayarları',
                'ordering': ['page_name'],
            },
        ),
    ]
