# Generated by Django 4.2.7 on 2025-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silinmiş'),
        ),
    ]
