# Generated by Django 4.2.7 on 2025-10-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contactmessage_deleted_at_contactmessage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='values',
            field=models.JSONField(default=list, help_text='[{"icon": "FaHeart", "title": "Sevgi ve Özen", "description": "..."}, ...]', verbose_name='Değerlerimiz'),
        ),
    ]
