# Generated by Django 5.2.7 on 2025-10-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aboutpage_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line1', models.CharField(default='Evcil Dostlarınız İçin', max_length=200, verbose_name='Ana Başlık Satır 1')),
                ('hero_title_line2', models.CharField(default='Kapsamlı Hizmetler', max_length=200, verbose_name='Ana Başlık Satır 2')),
                ('hero_description', models.TextField(default='Modern ekipmanlarımız ve uzman veteriner kadromuzla evcil hayvanlarınızın sağlığı için her türlü hizmeti sunuyoruz.', verbose_name='Hero Açıklama')),
                ('feature_pills', models.JSONField(default=list, help_text='[{"icon": "🏥", "text": "Modern Klinik"}, {"icon": "⚡", "text": "7/24 Acil Servis"}, {"icon": "👨\u200d⚕️", "text": "Uzman Kadro"}]', verbose_name='Özellik Pillleri')),
                ('stats', models.JSONField(default=list, help_text='[{"number": "21+", "label": "Hizmet Dalı", "icon": "🩺", "gradient": "from-emerald-500 to-cyan-500"}, ...]', verbose_name='İstatistikler')),
                ('cta_title', models.CharField(default='Daha Fazla Bilgi İçin', max_length=200, verbose_name='CTA Başlık')),
                ('cta_subtitle', models.CharField(default='Bize Ulaşın', max_length=200, verbose_name='CTA Alt Başlık')),
                ('cta_description', models.TextField(default='Size en uygun hizmeti bulmak ve randevu oluşturmak için 7/24 hizmetinizdeyiz', verbose_name='CTA Açıklama')),
                ('cta_phone', models.CharField(default='(0212) 123 45 67', max_length=50, verbose_name='CTA Telefon')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hizmetler Sayfası',
                'verbose_name_plural': 'Hizmetler Sayfası',
            },
        ),
    ]
