# Generated by Django 5.2.7 on 2025-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_servicespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, help_text="Boş bırakılırsa 'short_description' kullanılır", max_length=170, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text="Boş bırakılırsa 'title' kullanılır", max_length=70, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.CharField(blank=True, default='/og-service.jpg', max_length=255, verbose_name='OG Görsel URL'),
        ),
    ]
