# Generated by Django 5.2.7 on 2025-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_service_meta_description_service_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('initial', models.CharField(help_text='Örn: AB', max_length=2, verbose_name='İnisiyel')),
                ('rating', models.IntegerField(default=5, help_text='1-5 arası', verbose_name='Puan')),
                ('text', models.TextField(verbose_name='Yorum Metni')),
                ('date', models.CharField(help_text='Örn: 2 hafta önce', max_length=50, verbose_name='Tarih')),
                ('verified', models.BooleanField(default=True, verbose_name='Doğrulanmış')),
                ('local_guide', models.BooleanField(default=False, verbose_name='Yerel Rehber')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, help_text='Küçük numara önce gösterilir', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Yorumu',
                'verbose_name_plural': 'Google Yorumları',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="İstanbul'un En Güvenilir Veteriner Kliniği", max_length=200, verbose_name='Hero Başlık')),
                ('hero_subtitle', models.CharField(default='Modern ekipmanlarımız ve uzman veteriner kadromuzla evcil dostlarınızın sağlığı için 7/24 hizmetinizdeyiz', max_length=300, verbose_name='Hero Alt Başlık')),
                ('hero_cta_text', models.CharField(default='Randevu Al', max_length=50, verbose_name='Hero Buton Metni')),
                ('hero_cta_link', models.CharField(default='/randevu', max_length=200, verbose_name='Hero Buton Linki')),
                ('hero_secondary_cta_text', models.CharField(blank=True, default='Hizmetlerimiz', max_length=50, verbose_name='İkincil Buton Metni')),
                ('hero_secondary_cta_link', models.CharField(blank=True, default='/hizmetler', max_length=200, verbose_name='İkincil Buton Linki')),
                ('show_stats', models.BooleanField(default=True, verbose_name='İstatistikleri Göster')),
                ('stat1_number', models.CharField(default='15+', max_length=20, verbose_name='İstatistik 1 Sayı')),
                ('stat1_label', models.CharField(default='Yıllık Deneyim', max_length=100, verbose_name='İstatistik 1 Etiket')),
                ('stat2_number', models.CharField(default='10,000+', max_length=20, verbose_name='İstatistik 2 Sayı')),
                ('stat2_label', models.CharField(default='Mutlu Hayvan Sahibi', max_length=100, verbose_name='İstatistik 2 Etiket')),
                ('stat3_number', models.CharField(default='7/24', max_length=20, verbose_name='İstatistik 3 Sayı')),
                ('stat3_label', models.CharField(default='Acil Servis', max_length=100, verbose_name='İstatistik 3 Etiket')),
                ('stat4_number', models.CharField(default='25+', max_length=20, verbose_name='İstatistik 4 Sayı')),
                ('stat4_label', models.CharField(default='Uzman Veteriner', max_length=100, verbose_name='İstatistik 4 Etiket')),
                ('show_services', models.BooleanField(default=True, verbose_name='Hizmetleri Göster')),
                ('services_title', models.CharField(default='Hizmetlerimiz', max_length=200, verbose_name='Hizmetler Başlık')),
                ('services_subtitle', models.CharField(blank=True, default='Evcil dostlarınız için kapsamlı veteriner hizmetleri', max_length=300, verbose_name='Hizmetler Alt Başlık')),
                ('show_about', models.BooleanField(default=True, verbose_name='Hakkımızda Göster')),
                ('about_title', models.CharField(default='Biz Kimiz?', max_length=200, verbose_name='Hakkımızda Başlık')),
                ('about_description', models.TextField(default="İstanbul'un güvenilir veteriner kliniği olarak evcil dostlarınızın sağlığı için hizmet veriyoruz.", verbose_name='Hakkımızda Açıklama')),
                ('about_cta_text', models.CharField(default='Daha Fazla Bilgi', max_length=50, verbose_name='Hakkımızda Buton')),
                ('show_veterinarians', models.BooleanField(default=True, verbose_name='Veterinerleri Göster')),
                ('veterinarians_title', models.CharField(default='Uzman Kadromuz', max_length=200, verbose_name='Veterinerler Başlık')),
                ('veterinarians_subtitle', models.CharField(blank=True, default='Deneyimli ve uzman veteriner hekimlerimiz', max_length=300, verbose_name='Veterinerler Alt Başlık')),
                ('show_appointment_cta', models.BooleanField(default=True, verbose_name='Randevu CTA Göster')),
                ('appointment_cta_title', models.CharField(default='Randevu Almaya Hazır mısınız?', max_length=200, verbose_name='Randevu CTA Başlık')),
                ('appointment_cta_description', models.TextField(default='Evcil dostunuz için hemen online randevu oluşturun', verbose_name='Randevu CTA Açıklama')),
                ('appointment_cta_button', models.CharField(default='Hemen Randevu Al', max_length=50, verbose_name='Randevu Buton')),
                ('show_reviews', models.BooleanField(default=True, verbose_name='Yorumları Göster')),
                ('reviews_title', models.CharField(default='Müşteri Yorumları', max_length=200, verbose_name='Yorumlar Başlık')),
                ('reviews_subtitle', models.CharField(blank=True, default="Google'da aldığımız gerçek müşteri değerlendirmeleri", max_length=300, verbose_name='Yorumlar Alt Başlık')),
                ('reviews_rating', models.CharField(default='4.9', max_length=10, verbose_name='Ortalama Puan')),
                ('reviews_count', models.CharField(default='250+', max_length=20, verbose_name='Toplam Yorum')),
                ('reviews_cta_text', models.CharField(default="Tüm Yorumları Google'da Gör", max_length=100, verbose_name='Yorumlar Buton')),
                ('reviews_cta_link', models.URLField(blank=True, default='https://www.google.com/maps', verbose_name='Yorumlar Buton Link')),
                ('show_blog', models.BooleanField(default=True, verbose_name='Blog Göster')),
                ('blog_title', models.CharField(default='Blog Yazılarımız', max_length=200, verbose_name='Blog Başlık')),
                ('blog_subtitle', models.CharField(blank=True, default='Evcil hayvan bakımı hakkında faydalı bilgiler', max_length=300, verbose_name='Blog Alt Başlık')),
                ('show_contact', models.BooleanField(default=True, verbose_name='İletişim Göster')),
                ('contact_title', models.CharField(default='Bize Ulaşın', max_length=200, verbose_name='İletişim Başlık')),
                ('contact_description', models.TextField(default='Sorularınız için bizimle iletişime geçin', verbose_name='İletişim Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anasayfa',
                'verbose_name_plural': 'Anasayfa',
            },
        ),
    ]
