# Generated by Django 5.2.7 on 2025-10-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_googlereview_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_why_choose',
            field=models.BooleanField(default=True, verbose_name='Neden Biz Göster'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_features',
            field=models.JSONField(blank=True, default=list, help_text='[{"icon": "🏥", "title": "Modern Klinik", "description": "En son teknoloji ekipmanlar"}, ...]', verbose_name='Neden Biz Özellikleri'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_subtitle',
            field=models.CharField(blank=True, default='Modern teknoloji ve sevgi dolu yaklaşımımızla fark yaratıyoruz', max_length=300, verbose_name='Neden Biz Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_title',
            field=models.CharField(default='Neden Biz?', max_length=200, verbose_name='Neden Biz Başlık'),
        ),
    ]
