# Generated by Django 5.2.7 on 2025-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_homepage_show_why_choose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_features',
            field=models.JSONField(blank=True, default=list, help_text='[{"text": "Hızlı Randevu"}, {"text": "Uzman Kadro"}, {"text": "Modern Ekipman"}, {"text": "7/24 Hizmet"}]', verbose_name='Randevu Özellikleri'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_phone',
            field=models.CharField(default='(0212) 123 45 67', max_length=20, verbose_name='Randevu Telefon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_phone_link',
            field=models.CharField(default='+902121234567', max_length=20, verbose_name='Randevu Telefon Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_stat1_label',
            field=models.CharField(default='Google Puanı', max_length=50, verbose_name='Stat 1 Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_stat1_number',
            field=models.CharField(default='4.9', max_length=20, verbose_name='Stat 1 Sayı'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_stat2_label',
            field=models.CharField(default='Mutlu Hayvan', max_length=50, verbose_name='Stat 2 Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_stat2_number',
            field=models.CharField(default='5,000+', max_length=20, verbose_name='Stat 2 Sayı'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_stat3_label',
            field=models.CharField(default='Uzman Veteriner', max_length=50, verbose_name='Stat 3 Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='appointment_cta_stat3_number',
            field=models.CharField(default='15+', max_length=20, verbose_name='Stat 3 Sayı'),
        ),
    ]
