# Generated by Django 5.2.7 on 2025-10-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_homepage_appointment_cta_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
