# Generated by Django 5.2.7 on 2025-10-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_veterinarian_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Veteriner Kliniği', max_length=200, verbose_name='Site Başlığı')),
                ('site_logo_text', models.CharField(default='Veteriner', max_length=100, verbose_name='Logo Metni')),
                ('site_logo_subtitle', models.CharField(default='Veteriner Kliniği', max_length=100, verbose_name='Logo Alt Yazısı')),
                ('site_logo_emoji', models.CharField(default='🐾', max_length=10, verbose_name='Logo Emoji')),
                ('contact_phone', models.CharField(default='(0212) 123 45 67', max_length=20, verbose_name='Telefon Numarası')),
                ('contact_phone_link', models.CharField(default='+902121234567', max_length=20, verbose_name='Telefon Link')),
                ('contact_email', models.EmailField(default='info@veteriner.com', max_length=254, verbose_name='E-posta')),
                ('contact_address', models.TextField(default='Kadıköy, İstanbul', verbose_name='Adres')),
                ('footer_about_text', models.TextField(default='Sevimli dostlarınızın sağlığı için modern ekipman ve deneyimli kadromuzla 7/24 hizmetinizdeyiz. Onların mutluluğu bizim önceliğimiz.', verbose_name='Footer Hakkında Metni')),
                ('footer_facebook_url', models.URLField(blank=True, default='https://facebook.com/veteriner', verbose_name='Facebook URL')),
                ('footer_instagram_url', models.URLField(blank=True, default='https://instagram.com/veteriner', verbose_name='Instagram URL')),
                ('footer_twitter_url', models.URLField(blank=True, default='https://twitter.com/veteriner', verbose_name='Twitter URL')),
                ('working_hours_weekday', models.CharField(default='09:00 - 18:00', max_length=100, verbose_name='Hafta İçi')),
                ('working_hours_weekend', models.CharField(default='10:00 - 16:00', max_length=100, verbose_name='Hafta Sonu')),
                ('working_hours_info', models.CharField(default='7/24 Acil Servis', max_length=200, verbose_name='Ek Bilgi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
