# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_image',
            field=models.ImageField(blank=True, help_text='Logo resmi yükleyin (Tavsiye edilen: 200x200px)', null=True, upload_to='logos/', verbose_name='Logo Resmi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_emoji',
            field=models.CharField(default='🐾', help_text='Logo resmi yoksa emoji gösterilir', max_length=10, verbose_name='Logo Emoji'),
        ),
    ]
