# Generated by Django 5.2.7 on 2025-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_sitesettings_site_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_emoji',
            field=models.CharField(blank=True, default='🐾', help_text='Logo resmi yoksa emoji gösterilir', max_length=10, verbose_name='Logo Emoji'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_subtitle',
            field=models.CharField(blank=True, default='Veteriner Kliniği', max_length=100, verbose_name='Logo Alt Yazısı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_text',
            field=models.CharField(blank=True, default='Veteriner', max_length=100, verbose_name='Logo Metni'),
        ),
    ]
