# Generated by Django 5.0.1 on 2025-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_sitesettings_site_logo_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default='+905001234567', help_text='Uluslararası format: +90...', max_length=20, verbose_name='WhatsApp Numarası'),
        ),
    ]
