# Generated by Django 5.0.1 on 2025-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sitesettings_contact_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='hero_phone',
            field=models.CharField(default='(0212) 123 45 67', max_length=50, verbose_name='Hero Telefon (Görünen)'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_phone_link',
            field=models.CharField(default='+902121234567', max_length=50, verbose_name='Hero Telefon Link (tel:)'),
        ),
    ]
