services:
  # Django Backend
  - type: web
    name: petkey-backend
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn petkey_api.wsgi:application"
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        value: postgresql://veteriner_database_user:jBI2wtEi2KZ3EmXs0peOKBAockvhQeUj@dpg-d3t71j63jp1c738imri0-a/veteriner_database
      - key: CORS_ALLOWED_ORIGINS
        value: https://petkey-frontend-9cbf.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://petkey-frontend-9cbf.onrender.com
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@petkey.com
      - key: ADMIN_PASSWORD
        value: PetKey2024Admin!
      - key: RESET_DATA
        value: true

  # React Frontend
  - type: web
    name: petkey-frontend
    runtime: static
    buildCommand: rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://petkey-backend-9cbf.onrender.com
